/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_feilong_myjnitest_MainActivity */

#ifndef _Included_com_feilong_myjnitest_MainActivity
#define _Included_com_feilong_myjnitest_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_feilong_myjnitest_MainActivity
 * Method:    getHelloWorldString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_feilong_myjnitest_MainActivity_getHelloWorldString
  (JNIEnv *, jobject);

/*
 * Class:     com_feilong_myjnitest_MainActivity
 * Method:    getHelloCoderString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_feilong_myjnitest_MainActivity_getHelloCoderString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
